# Generated by Django 6.0.6 on 2026-07-09 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Category (e.g., Backend)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
