# Generated by Django 6.0.6 on 2026-07-08 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Category (e.g., Backend)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name (if applicable)')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Sector (if applicable)')),
                ('payment_verification_status', models.BooleanField(default=False, verbose_name='Payment Verification Status')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Spent ($)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Professional Title')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('hourly_rate', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate ($)')),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PART_TIME', 'Part-time Available'), ('BUSY', 'Busy')], db_index=True, default='AVAILABLE', max_length=20)),
                ('job_success_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Job Success Score (%)')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Earnings ($)')),
                ('total_hours_worked', models.PositiveIntegerField(default=0, verbose_name='Total Hours Worked')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Identity/Skill Verified')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Personal Website URL')),
                ('english_level', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient'), ('NATIVE', 'Native / Bilingual')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperEducation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='University / Institution Name')),
                ('degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree (e.g., B.Sc., M.Sc.)')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field of Study')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Currently Studying')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Achievements')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.developerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperCertification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Certification Name')),
                ('issuing_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing Organization')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credential ID')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='Credential URL')),
                ('verification_url', models.URLField(blank=True, null=True, verbose_name='Verification URL')),
                ('path_to_certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate File')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.developerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Live Project URL')),
                ('repository_url', models.URLField(blank=True, null=True, verbose_name='Repository (GitHub/GitLab) URL')),
                ('technologies_used', models.JSONField(blank=True, default=list, verbose_name='Technologies Used (Array)')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='profiles.developerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid-Level'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], db_index=True, default='MID', max_length=20)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='profiles.developerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_developers', to='profiles.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('developer', 'skill'), name='unique_developer_skill')],
            },
        ),
    ]
