# Generated by Django 6.0.6 on 2026-07-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_developers', to='skills.skill'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
